//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication26.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.MyEvents = new HashSet<MyEvent>();
            this.Friends = new HashSet<Friend>();
        }
    
        [ReadOnly(true)]
        public int MemberId { get; set; }
        public string MemberUsername { get; set; }
        public string MemberPassword { get; set; }
        [DisplayName("Member Name")]
        public string MemberName { get; set; }
        [DisplayName("Member Address")]
        public string MemberAddress { get; set; }
        [DisplayName("Contact Number")]
        public int MemberContactNumber { get; set; }
        [DisplayName("Date of Birth")]
        public string MemberDateofBirth { get; set; }
        [DisplayName("Member Gender")]
        public string MemberGender { get; set; }
        public int MemberPostId { get; set; }
        public string MemberBio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyEvent> MyEvents { get; set; }
        public virtual Message Message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friend> Friends { get; set; }
    }
}
