//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication26.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class MyEvent
    {
        public int EventId { get; set; }
        public int MemberId { get; set; }
        [DisplayName("Event Interest")]
        public string MyEventsIntrests { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Member Member { get; set; }
    }
}
